kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-local-weather-api-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8001
        protocol: TCP
