apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api
  namespace: k8s-local-weather-api
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/instance: weather-api
spec:
  rules:
    - host: "weather-api.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-api
                port:
                  number: 80
