apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: k8s-local-weather-api
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/instance: weather-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/instance: weather-api
